In [1]:
import pandas as pd
import numpy as np

In [2]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [9]:
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),columns=["column1", "column2", "column3", "column4"],
             index=["row1", "row2", "row3", "row4", "row5"])


In [10]:
type(df)


pandas.core.frame.DataFrame

In [11]:
df

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [12]:
df.head()

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [13]:
df.tail()

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [14]:
df.head(2)

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7

In [15]:
df.tail(3)

column1  column2  column3  column4
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [16]:
df.describe()

column1    column2    column3    column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [17]:
df[['column1', 'column2']]

column1  column2
row1        0        1
row2        4        5
row3        8        9
row4       12       13
row5       16       17

In [18]:
type(df[['column1', 'column2']])

pandas.core.frame.DataFrame

In [19]:
df['column1']

row1     0
row2     4
row3     8
row4    12
row5    16
Name: column1, dtype: int64

In [20]:
type(df['column1'])

pandas.core.series.Series

In [21]:
df.loc[['row1','row4']]

column1  column2  column3  column4
row1        0        1        2        3
row4       12       13       14       15

In [22]:
df.iloc[0:4,:]

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15

In [23]:
df.iloc[0:3,0:2]

column1  column2
row1        0        1
row2        4        5
row3        8        9

In [25]:
df.iloc[2:4,1:3].values

array([[ 9, 10],
       [13, 14]])

In [26]:
np.nan

nan

In [28]:
df=pd.DataFrame(data=[[1,np.nan,2], [1,3,4], [5,4,3]],index=["row1", "row2", "row3"],
                columns=["column1", "column2", "column3"])
df

column1  column2  column3
row1        1      NaN        2
row2        1      3.0        4
row3        5      4.0        3

In [29]:
df.isnull()

column1  column2  column3
row1    False     True    False
row2    False    False    False
row3    False    False    False

In [30]:
df.isnull().sum()

column1    0
column2    1
column3    0
dtype: int64

In [31]:
df.isna().sum()

column1    0
column2    1
column3    0
dtype: int64

In [32]:
type(np.nan)

float

In [33]:
df

column1  column2  column3
row1        1      NaN        2
row2        1      3.0        4
row3        5      4.0        3

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, row1 to row3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   column1  3 non-null      int64  
 1   column2  2 non-null      float64
 2   column3  3 non-null      int64  
dtypes: float64(1), int64(2)
memory usage: 204.0+ bytes


In [35]:
df.head()

column1  column2  column3
row1        1      NaN        2
row2        1      3.0        4
row3        5      4.0        3

In [36]:
df['column1'].value_counts()

1    2
5    1
Name: column1, dtype: int64

In [37]:
df['column1'].unique()

array([1, 5])

In [38]:
df['column1'].nunique()

2